import type { AppUser, DeviceStatus, LogEntry, PairedDevice } from "@/types";

// ─── Mock Devices ────────────────────────────────────────────────────────────
export const MOCK_DEVICES: PairedDevice[] = [
  {
    deviceId: "RKSH-A3F7",
    name: "Home",
    online: true,
    lastSeen: new Date().toISOString(),
  },
  {
    deviceId: "RKSH-B9C2",
    name: "Office",
    online: false,
    lastSeen: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
];

// ─── Mock Device Status ───────────────────────────────────────────────────────
export const MOCK_STATUS: DeviceStatus = {
  deviceId: "RKSH-A3F7",
  name: "Home",
  online: true,
  lastSeen: new Date().toISOString(),
  arm1: false,
  arm2: false,
  acPower: true,
  gsmSignal: 87,
  gsmQuality: "Excellent",
  sirenActive: false,
  lastEvent: "DISARMED ALL",
};

// ─── Mock User ───────────────────────────────────────────────────────────────
export const MOCK_USER: AppUser = {
  uid: "usr_demo_001",
  email: "admin@rakshak.app",
  displayName: "Admin User",
};

// ─── Mock Logs ───────────────────────────────────────────────────────────────
const now = Date.now();
const mins = (n: number) => new Date(now - n * 60 * 1000).toISOString();

export const MOCK_LOGS: LogEntry[] = [
  {
    id: "log_001",
    timestamp: mins(3),
    type: "disarmed_all",
    message: "All zones disarmed via app",
    source: "APP",
    arm1: false,
    arm2: false,
  },
  {
    id: "log_002",
    timestamp: mins(8),
    type: "alarm",
    message: "Sensor 3 triggered — Front Door Motion",
    source: "DEVICE",
    arm1: true,
    arm2: false,
  },
  {
    id: "log_003",
    timestamp: mins(9),
    type: "arm1_activated",
    message: "Zone 1 armed — Away Mode",
    source: "APP",
    arm1: true,
    arm2: false,
  },
  {
    id: "log_004",
    timestamp: mins(35),
    type: "arm2_activated",
    message: "Zone 2 armed — Home Perimeter",
    source: "SCREEN",
    arm1: false,
    arm2: true,
  },
  {
    id: "log_005",
    timestamp: mins(62),
    type: "arm2_disarmed",
    message: "Zone 2 disarmed via SMS command",
    source: "SMS",
    arm1: false,
    arm2: false,
  },
  {
    id: "log_006",
    timestamp: mins(90),
    type: "ac_cut",
    message: "Mains AC power lost — running on battery",
    source: "DEVICE",
    arm1: false,
    arm2: false,
  },
  {
    id: "log_007",
    timestamp: mins(95),
    type: "ac_restored",
    message: "Mains AC power restored",
    source: "DEVICE",
    arm1: false,
    arm2: false,
  },
  {
    id: "log_008",
    timestamp: mins(120),
    type: "sos",
    message: "SOS button pressed — manual panic alert",
    source: "DEVICE",
    arm1: false,
    arm2: false,
  },
  {
    id: "log_009",
    timestamp: mins(145),
    type: "alarm",
    message: "Sensor 1 triggered — Living Room PIR",
    source: "DEVICE",
    arm1: true,
    arm2: true,
  },
  {
    id: "log_010",
    timestamp: mins(146),
    type: "disarmed_all",
    message: "All zones disarmed via remote",
    source: "REMOTE",
    arm1: false,
    arm2: false,
  },
  {
    id: "log_011",
    timestamp: mins(200),
    type: "device_offline",
    message: "Device RKSH-A3F7 went offline — heartbeat timeout",
    source: "DEVICE",
    arm1: false,
    arm2: false,
  },
  {
    id: "log_012",
    timestamp: mins(215),
    type: "device_online",
    message: "Device RKSH-A3F7 reconnected to cloud",
    source: "DEVICE",
    arm1: false,
    arm2: false,
  },
  {
    id: "log_013",
    timestamp: mins(300),
    type: "arm1_disarmed",
    message: "Zone 1 disarmed — entry by authorised user",
    source: "SCREEN",
    arm1: false,
    arm2: false,
  },
  {
    id: "log_014",
    timestamp: mins(305),
    type: "arm1_activated",
    message: "Zone 1 armed — leaving for work",
    source: "APP",
    arm1: true,
    arm2: false,
  },
  {
    id: "log_015",
    timestamp: mins(480),
    type: "alarm",
    message: "Sensor 5 triggered — Back Window Reed Switch",
    source: "DEVICE",
    arm1: true,
    arm2: false,
  },
  {
    id: "log_016",
    timestamp: mins(481),
    type: "disarmed_all",
    message: "Emergency disarm — all zones cleared",
    source: "APP",
    arm1: false,
    arm2: false,
  },
  {
    id: "log_017",
    timestamp: mins(600),
    type: "ac_cut",
    message: "AC power cut — possible power outage",
    source: "DEVICE",
    arm1: false,
    arm2: false,
  },
  {
    id: "log_018",
    timestamp: mins(610),
    type: "ac_restored",
    message: "Power restored — system operational",
    source: "DEVICE",
    arm1: false,
    arm2: false,
  },
  {
    id: "log_019",
    timestamp: mins(720),
    type: "arm2_activated",
    message: "Zone 2 armed — night perimeter set",
    source: "SCREEN",
    arm1: false,
    arm2: true,
  },
  {
    id: "log_020",
    timestamp: mins(1440),
    type: "device_online",
    message: "System boot — Rakshak RKSH-A3F7 connected",
    source: "DEVICE",
    arm1: false,
    arm2: false,
  },
];
