/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'receiveSms' : IDL.Bool,
  'phone' : IDL.Text,
  'receiveCall' : IDL.Bool,
});
export const Timestamp = IDL.Int;
export const LogEntry = IDL.Record({
  'id' : IDL.Text,
  'armedBy' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'sensorId' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'eventType' : IDL.Text,
});
export const Sensor = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'signalPercent' : IDL.Opt(IDL.Nat),
  'batteryPercent' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'type' : IDL.Text,
  'zone' : IDL.Text,
  'bypassed' : IDL.Bool,
  'lastTriggered' : IDL.Opt(Timestamp),
});
export const AppSettingsPublic = IDL.Record({
  'pin' : IDL.Text,
  'notificationsEnabled' : IDL.Bool,
  'sirenDuration' : IDL.Text,
  'simStatus' : IDL.Text,
  'deviceIp' : IDL.Text,
  'entryDelay' : IDL.Nat,
  'firmwareVersion' : IDL.Text,
  'exitDelay' : IDL.Nat,
});
export const SystemStatePublic = IDL.Record({
  'armed' : IDL.Bool,
  'signalStrength' : IDL.Nat,
  'lastArmedTime' : IDL.Opt(Timestamp),
  'mode' : IDL.Text,
  'armedBy' : IDL.Text,
  'triggeredSensorId' : IDL.Opt(IDL.Text),
  'connectionStatus' : IDL.Text,
});

export const idlService = IDL.Service({
  'addContact' : IDL.Func([Contact], [IDL.Text], []),
  'addLog' : IDL.Func([LogEntry], [IDL.Text], []),
  'addSensor' : IDL.Func([Sensor], [IDL.Text], []),
  'armSystem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'changePin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteContact' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteSensor' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'disarmSystem' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getLogs' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
  'getSensors' : IDL.Func([], [IDL.Vec(Sensor)], ['query']),
  'getSettings' : IDL.Func([], [AppSettingsPublic], ['query']),
  'getStatus' : IDL.Func([], [SystemStatePublic], ['query']),
  'seedDemoData' : IDL.Func([], [IDL.Bool], []),
  'updateContact' : IDL.Func([IDL.Text, Contact], [IDL.Bool], []),
  'updateSensorBypass' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  'updateSettings' : IDL.Func([AppSettingsPublic], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'receiveSms' : IDL.Bool,
    'phone' : IDL.Text,
    'receiveCall' : IDL.Bool,
  });
  const Timestamp = IDL.Int;
  const LogEntry = IDL.Record({
    'id' : IDL.Text,
    'armedBy' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'sensorId' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'eventType' : IDL.Text,
  });
  const Sensor = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'signalPercent' : IDL.Opt(IDL.Nat),
    'batteryPercent' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'type' : IDL.Text,
    'zone' : IDL.Text,
    'bypassed' : IDL.Bool,
    'lastTriggered' : IDL.Opt(Timestamp),
  });
  const AppSettingsPublic = IDL.Record({
    'pin' : IDL.Text,
    'notificationsEnabled' : IDL.Bool,
    'sirenDuration' : IDL.Text,
    'simStatus' : IDL.Text,
    'deviceIp' : IDL.Text,
    'entryDelay' : IDL.Nat,
    'firmwareVersion' : IDL.Text,
    'exitDelay' : IDL.Nat,
  });
  const SystemStatePublic = IDL.Record({
    'armed' : IDL.Bool,
    'signalStrength' : IDL.Nat,
    'lastArmedTime' : IDL.Opt(Timestamp),
    'mode' : IDL.Text,
    'armedBy' : IDL.Text,
    'triggeredSensorId' : IDL.Opt(IDL.Text),
    'connectionStatus' : IDL.Text,
  });
  
  return IDL.Service({
    'addContact' : IDL.Func([Contact], [IDL.Text], []),
    'addLog' : IDL.Func([LogEntry], [IDL.Text], []),
    'addSensor' : IDL.Func([Sensor], [IDL.Text], []),
    'armSystem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'changePin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteContact' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteSensor' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'disarmSystem' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getLogs' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    'getSensors' : IDL.Func([], [IDL.Vec(Sensor)], ['query']),
    'getSettings' : IDL.Func([], [AppSettingsPublic], ['query']),
    'getStatus' : IDL.Func([], [SystemStatePublic], ['query']),
    'seedDemoData' : IDL.Func([], [IDL.Bool], []),
    'updateContact' : IDL.Func([IDL.Text, Contact], [IDL.Bool], []),
    'updateSensorBypass' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
    'updateSettings' : IDL.Func([AppSettingsPublic], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };