/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettingsPublic {
  'pin' : string,
  'notificationsEnabled' : boolean,
  'sirenDuration' : string,
  'simStatus' : string,
  'deviceIp' : string,
  'entryDelay' : bigint,
  'firmwareVersion' : string,
  'exitDelay' : bigint,
}
export interface Contact {
  'id' : string,
  'name' : string,
  'role' : string,
  'receiveSms' : boolean,
  'phone' : string,
  'receiveCall' : boolean,
}
export interface LogEntry {
  'id' : string,
  'armedBy' : [] | [string],
  'description' : string,
  'sensorId' : [] | [string],
  'timestamp' : Timestamp,
  'eventType' : string,
}
export interface Sensor {
  'id' : string,
  'status' : string,
  'signalPercent' : [] | [bigint],
  'batteryPercent' : [] | [bigint],
  'name' : string,
  'type' : string,
  'zone' : string,
  'bypassed' : boolean,
  'lastTriggered' : [] | [Timestamp],
}
export interface SystemStatePublic {
  'armed' : boolean,
  'signalStrength' : bigint,
  'lastArmedTime' : [] | [Timestamp],
  'mode' : string,
  'armedBy' : string,
  'triggeredSensorId' : [] | [string],
  'connectionStatus' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addContact' : ActorMethod<[Contact], string>,
  'addLog' : ActorMethod<[LogEntry], string>,
  'addSensor' : ActorMethod<[Sensor], string>,
  'armSystem' : ActorMethod<[string, string], boolean>,
  'changePin' : ActorMethod<[string, string], boolean>,
  'deleteContact' : ActorMethod<[string], boolean>,
  'deleteSensor' : ActorMethod<[string], boolean>,
  'disarmSystem' : ActorMethod<[string], boolean>,
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getLogs' : ActorMethod<[], Array<LogEntry>>,
  'getSensors' : ActorMethod<[], Array<Sensor>>,
  'getSettings' : ActorMethod<[], AppSettingsPublic>,
  'getStatus' : ActorMethod<[], SystemStatePublic>,
  'seedDemoData' : ActorMethod<[], boolean>,
  'updateContact' : ActorMethod<[string, Contact], boolean>,
  'updateSensorBypass' : ActorMethod<[string, boolean], boolean>,
  'updateSettings' : ActorMethod<[AppSettingsPublic], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];