/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Sensor {
    id: string;
    status: string;
    signalPercent?: bigint;
    batteryPercent?: bigint;
    name: string;
    type: string;
    zone: string;
    bypassed: boolean;
    lastTriggered?: Timestamp;
}
export type Timestamp = bigint;
export interface LogEntry {
    id: string;
    armedBy?: string;
    description: string;
    sensorId?: string;
    timestamp: Timestamp;
    eventType: string;
}
export interface Contact {
    id: string;
    name: string;
    role: string;
    receiveSms: boolean;
    phone: string;
    receiveCall: boolean;
}
export interface SystemStatePublic {
    armed: boolean;
    signalStrength: bigint;
    lastArmedTime?: Timestamp;
    mode: string;
    armedBy: string;
    triggeredSensorId?: string;
    connectionStatus: string;
}
export interface AppSettingsPublic {
    pin: string;
    notificationsEnabled: boolean;
    sirenDuration: string;
    simStatus: string;
    deviceIp: string;
    entryDelay: bigint;
    firmwareVersion: string;
    exitDelay: bigint;
}
export interface backendInterface {
    addContact(contact: Contact): Promise<string>;
    addLog(entry: LogEntry): Promise<string>;
    addSensor(sensor: Sensor): Promise<string>;
    armSystem(mode: string, pin: string): Promise<boolean>;
    changePin(oldPin: string, newPin: string): Promise<boolean>;
    deleteContact(id: string): Promise<boolean>;
    deleteSensor(id: string): Promise<boolean>;
    disarmSystem(pin: string): Promise<boolean>;
    getContacts(): Promise<Array<Contact>>;
    getLogs(): Promise<Array<LogEntry>>;
    getSensors(): Promise<Array<Sensor>>;
    getSettings(): Promise<AppSettingsPublic>;
    getStatus(): Promise<SystemStatePublic>;
    seedDemoData(): Promise<boolean>;
    updateContact(id: string, contact: Contact): Promise<boolean>;
    updateSensorBypass(id: string, bypassed: boolean): Promise<boolean>;
    updateSettings(settings: AppSettingsPublic): Promise<boolean>;
}
import type { LogEntry as _LogEntry, Sensor as _Sensor, SystemStatePublic as _SystemStatePublic, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addContact(arg0: Contact): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContact(arg0);
            return result;
        }
    }
    async addLog(arg0: LogEntry): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addLog(to_candid_LogEntry_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLog(to_candid_LogEntry_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSensor(arg0: Sensor): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addSensor(to_candid_Sensor_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSensor(to_candid_Sensor_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async armSystem(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.armSystem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.armSystem(arg0, arg1);
            return result;
        }
    }
    async changePin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changePin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePin(arg0, arg1);
            return result;
        }
    }
    async deleteContact(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async deleteSensor(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSensor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSensor(arg0);
            return result;
        }
    }
    async disarmSystem(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.disarmSystem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disarmSystem(arg0);
            return result;
        }
    }
    async getContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContacts();
            return result;
        }
    }
    async getLogs(): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogs();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogs();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSensors(): Promise<Array<Sensor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSensors();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSensors();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<AppSettingsPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getStatus(): Promise<SystemStatePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatus();
                return from_candid_SystemStatePublic_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatus();
            return from_candid_SystemStatePublic_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedDemoData(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async updateContact(arg0: string, arg1: Contact): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContact(arg0, arg1);
            return result;
        }
    }
    async updateSensorBypass(arg0: string, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSensorBypass(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSensorBypass(arg0, arg1);
            return result;
        }
    }
    async updateSettings(arg0: AppSettingsPublic): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
}
function from_candid_LogEntry_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LogEntry): LogEntry {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Sensor_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sensor): Sensor {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_SystemStatePublic_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemStatePublic): SystemStatePublic {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    signalPercent: [] | [bigint];
    batteryPercent: [] | [bigint];
    name: string;
    type: string;
    zone: string;
    bypassed: boolean;
    lastTriggered: [] | [_Timestamp];
}): {
    id: string;
    status: string;
    signalPercent?: bigint;
    batteryPercent?: bigint;
    name: string;
    type: string;
    zone: string;
    bypassed: boolean;
    lastTriggered?: Timestamp;
} {
    return {
        id: value.id,
        status: value.status,
        signalPercent: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.signalPercent)),
        batteryPercent: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.batteryPercent)),
        name: value.name,
        type: value.type,
        zone: value.zone,
        bypassed: value.bypassed,
        lastTriggered: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lastTriggered))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    armed: boolean;
    signalStrength: bigint;
    lastArmedTime: [] | [_Timestamp];
    mode: string;
    armedBy: string;
    triggeredSensorId: [] | [string];
    connectionStatus: string;
}): {
    armed: boolean;
    signalStrength: bigint;
    lastArmedTime?: Timestamp;
    mode: string;
    armedBy: string;
    triggeredSensorId?: string;
    connectionStatus: string;
} {
    return {
        armed: value.armed,
        signalStrength: value.signalStrength,
        lastArmedTime: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lastArmedTime)),
        mode: value.mode,
        armedBy: value.armedBy,
        triggeredSensorId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.triggeredSensorId)),
        connectionStatus: value.connectionStatus
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    armedBy: [] | [string];
    description: string;
    sensorId: [] | [string];
    timestamp: _Timestamp;
    eventType: string;
}): {
    id: string;
    armedBy?: string;
    description: string;
    sensorId?: string;
    timestamp: Timestamp;
    eventType: string;
} {
    return {
        id: value.id,
        armedBy: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.armedBy)),
        description: value.description,
        sensorId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.sensorId)),
        timestamp: value.timestamp,
        eventType: value.eventType
    };
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LogEntry>): Array<LogEntry> {
    return value.map((x)=>from_candid_LogEntry_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Sensor>): Array<Sensor> {
    return value.map((x)=>from_candid_Sensor_n10(_uploadFile, _downloadFile, x));
}
function to_candid_LogEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogEntry): _LogEntry {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Sensor_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sensor): _Sensor {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    armedBy?: string;
    description: string;
    sensorId?: string;
    timestamp: Timestamp;
    eventType: string;
}): {
    id: string;
    armedBy: [] | [string];
    description: string;
    sensorId: [] | [string];
    timestamp: _Timestamp;
    eventType: string;
} {
    return {
        id: value.id,
        armedBy: value.armedBy ? candid_some(value.armedBy) : candid_none(),
        description: value.description,
        sensorId: value.sensorId ? candid_some(value.sensorId) : candid_none(),
        timestamp: value.timestamp,
        eventType: value.eventType
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    signalPercent?: bigint;
    batteryPercent?: bigint;
    name: string;
    type: string;
    zone: string;
    bypassed: boolean;
    lastTriggered?: Timestamp;
}): {
    id: string;
    status: string;
    signalPercent: [] | [bigint];
    batteryPercent: [] | [bigint];
    name: string;
    type: string;
    zone: string;
    bypassed: boolean;
    lastTriggered: [] | [_Timestamp];
} {
    return {
        id: value.id,
        status: value.status,
        signalPercent: value.signalPercent ? candid_some(value.signalPercent) : candid_none(),
        batteryPercent: value.batteryPercent ? candid_some(value.batteryPercent) : candid_none(),
        name: value.name,
        type: value.type,
        zone: value.zone,
        bypassed: value.bypassed,
        lastTriggered: value.lastTriggered ? candid_some(value.lastTriggered) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
